version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_USER=balatro
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=balatro
      - POSTGRES_PASSWORD=balatropass
      - POSTGRES_PORT=5432

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=balatro
      - POSTGRES_PASSWORD=balatropass
      - POSTGRES_DB=balatro
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: