version: '3.8'

networks:
  balatro-net:
    driver: bridge

services:
  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    networks:
      - balatro-net
    # The frontend is now exposed via Cloudflare Tunnel, not a host port.

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    networks:
      - balatro-net

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - balatro-net

  postgres:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - balatro-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --url http://frontend:80
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - frontend
    networks:
      - balatro-net

volumes:
  postgres_data: