version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
  backend:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
networks:
  default:
    name: balatro-network